apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx-ns
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 82        # service port (cluster internal)
      targetPort: 80  # container port
      nodePort: 30082 # external node port (30000–32767 range)


